<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0;net472</TargetFrameworks>
    <RootNamespace>OverKizApi.TestConsole</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <Company>Neil Colvin</Company>
    <Copyright>Copyright ©2026 Neil Colvin</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OverKizApi\OverKizApi.csproj" />
  </ItemGroup>

</Project>

